trigger:
- release/*

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo PipelineVariable $(PipelineVariable)
    - bash: echo Build.BuildNumber $(Build.BuildNumber)
    - bash: echo Build.BuildId $(Build.BuildId)
    - bash: echo Build.SourceBranchName $(Build.SourceBranchName)
    - bash: echo Build.SourcesDirectory $(Build.SourcesDirectory)
    - bash: echo System.DefaultWorkingDirectory $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo Build.ArtifactStagingDirectory $(Build.ArtifactStagingDirectory)


  # - job: SecondJob
  #   steps:
  #   - bash: echo Build SecondJob



##ctrl + k + c - comment
##ctrl + k + u - uncomment

# - stage: DevDeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo Build DevDeployJob
#     - bash: echo $(environment)DevDeployJob
# - stage: QADeploy
#   variables:
#     environment: Dev
#   dependsOn: Build
#   jobs:
#   - job: QADeployJob
#     steps:
#     - bash: echo DeployJob
# - stage: ProdDeploy
#   dependsOn: 
#     - DevDeploy
#     - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - bash: echo ProdDeployJob
